version: "3.7"

services:
  # image project
  php74:
    build:
      context: .
      dockerfile: docker_config/Dockerfile
      args:
        user: macrineeu
        uid: 1000
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8022:80"
    volumes:
      - ./:/var/www
      - ./docker_config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  # db mysql
  database:
    image: mysql:5.6
    environment:
      - "MYSQL_ROOT_PASSWORD=963741"
      - "MYSQL_DATABASE=erp_youcan"
    ports:
      - "3307:3306"
    volumes:
      - "./database/mysql/:/var/lib/mysql"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge